Migrate CI to GitHub Actions
icatproject/authn.db pull request #9
Opened 2022-03-03 09:13 UTC by VKTB

2022-03-03 09:22 UTC, VKTB commented
This PR should not be merged until https://github.com/icatproject-contrib/icat-ansible/pull/72 is merged and the TODO below is addressed
https://github.com/icatproject/authn.db/blob/d1fb4a8a70b45241964df0ee6516c2f6a989fd7c/.github/workflows/ci-build.yml#L44-L45

2022-03-03 13:26 UTC, VKTB commented
TODO comment was addressed in https://github.com/icatproject/authn.db/pull/9/commits/557871322cef9394c7db07da5c7e75654c7d98ef after https://github.com/icatproject-contrib/icat-ansible/pull/72 was merged so this PR can be merged as soon as it is approved.

2022-03-07 11:24 UTC, patrick-austin approved these changes
Looks good to me, old Travis tests didn't seem to be running the integration test(s) so good that this catches them.

2022-03-08 10:51 UTC, patrick-austin requested changes
See comments on https://github.com/icatproject/authn.ldap/pull/12

2022-03-08 10:51 UTC, patrick-austin commented on .github/workflows/ci-build.yml
> +        run: mvn failsafe:integration-test -B
```suggestion
        run: |
          mvn failsafe:integration-test -B
          mvn failsafe:verify
```

2022-03-08 12:22 UTC, patrick-austin approved these changes

2022-03-21 09:01 UTC, merged